name: coffea-env
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.13
  - coffea=2025.7.3
  - awkward=2.8.7
  - pip
  - conda
  - conda-pack
  - dill
  - xrootd
  - ndcctools>=7.14.11
  - numpy
  - setuptools=80.9.0
  - git
  - pyyaml
