name: coffea-env
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - pip
  - conda
  - conda-pack
  - dill
  - xrootd
  - ndcctools
  - setuptools==70.3.0
  - git
  - pyyaml
  - pip:
      - coffea==2025.7.3
      - awkward==2.8.7
